Fixed OWASP ZAP Docker network

diff --git a/netflix-clone-app/Jenkinsfile-zap b/netflix-clone-app/Jenkinsfile-zap
--- a/netflix-clone-app/Jenkinsfile-zap
+++ b/netflix-clone-app/Jenkinsfile-zap
@@ -6,7 +6,10 @@ pipeline {
         stage('Check Application') {
             steps {
                 sh '''
-                docker ps | grep netflix-app
+                docker ps | grep netflix-app || {
+                    echo "Netflix application is not running!"
+                    exit 1
+                }
                 '''
             }
         }
@@ -15,19 +18,22 @@ pipeline {
             steps {
                 sh '''
                 mkdir -p zap-report
+                chmod -R 777 zap-report
 
                 docker run --rm \
-                  --network host \
+                  --user root \
+                  --network devsecops-network \
                   -v $WORKSPACE/zap-report:/zap/wrk \
                   zaproxy/zap-stable \
                   zap-baseline.py \
-                  -t http://host.docker.internal:3000 \
-                  -r zap-report.html
+                  -t http://netflix-app \
+                  -r zap-report.html \
+                  -I
                 '''
             }
         }
 
-        stage('Publish Report') {
+        stage('Publish ZAP Report') {
             steps {
                 publishHTML([
                     allowMissing: false,
@@ -42,12 +48,17 @@ pipeline {
     }
 
     post {
+
+        always {
+            archiveArtifacts artifacts: 'zap-report/*', allowEmptyArchive: true
+        }
+
         success {
-            echo "DAST Scan Completed Successfully"
+            echo 'DAST Scan Completed Successfully!'
         }
 
         failure {
-            echo "DAST Scan Failed"
+            echo 'DAST Scan Failed!'
         }
     }
 }
